version: '3.7'

services:

  web:
    build: .
    command: > 
          sh -c  "python manage.py migrate --noinput &&
                  python manage.py runserver 0.0.0.0:8000 &&
                  gunicorn --workers=2 --bind=0.0.0.0:8000 tubers.wsgi:application"
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - tubers_network
  
  worker:
    build: .
    command: python manage.py rqworker default
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    depends_on:
      - web
    links:
      - web:web
    networks:
      - tubers_network

networks:
  tubers_network:
    driver: bridge